// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Rossko_test.Model;
using System;

namespace Rossko_test.Migrations
{
    [DbContext(typeof(RosskoContext))]
    partial class RosskoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rossko_test.Model.OptionsArray", b =>
                {
                    b.Property<string>("Keyword")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("OptionsList");

                    b.HasKey("Keyword");

                    b.ToTable("OptionsArrays");
                });
#pragma warning restore 612, 618
        }
    }
}
